### ISSUE TITLE
Example of how to edit redGenRun.py ?

### ISSUE THREAD

**Issue by Maj-ew** [LukachoLombardi/redGen#1]
So I have multiple logins and passwords ready but I don't know how exactly should it look like there?
Like actually it's so ununderstandable
```
import redGen

print(redGen.generate_accounts(30, "gfsadgsdg", "Password333"))
```

so what should I I just od it like 

```
import redGen

print(redGen.generate_accounts(30, "gfsadgsdg", "Password333", "username2", "Password2", "username3", "Password3"))
```
????
nah it doesn't work

**Comment by LukachoLombardi** [comment]
maybe I should've explained it better😅 The script currently uses the same base name and the same password for all accounts. So the first argument should be a name, and the second should be a password. The script will just add numbers to the base name for every account so if you start it with "abcd" as a base name with 16 accounts to generate, you'll get an array of accounts ranging from "abcd0" to "abcd15", all with the same password you specified. I know it isn't the best solution, so maybe I'll change it soon

**Comment by LukachoLombardi** [comment]
so you only need one name and one password

**Comment by Maj-ew** [comment]
yeah I see now it's just 1 2 3 4 5 6 7 8...
but I think that will be easy to detect for reddit

**Comment by LukachoLombardi** [comment]
Tbh I dont think so because there are probably 100 new accounts every second so they wouldn't really be able to pinpoint when similar names are just a coincidence and when they're not, especially if they're all created from different locations

**Comment by Maj-ew** [comment]
I mean literaly gasdgasdg0 gasdgasdg1 gasdgasdg2 gasdgasdg3 gasdgasdg4 it's really easy to spot if this is not a coincidence lol. Especially that I wanted to try these accounts out on r/place

**Comment by LukachoLombardi** [comment]
I think I'll rewrite the script anyway, so that probably won't be a problem anymore

**Comment by Maj-ew** [comment]
Yeah I mean this script was kind of good so far, did the best job but can't tell if it actually works since I didn't even have any output txt with logins and passwords.
