### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by MoeenTheSkid** [LukachoLombardi/redGen#3]
D:\Disk\Downloads\Website Botting Tools\Reddit\redditaccountgeneratortest\redGen-main>py redGenRun.py
The system cannot find the file D:\Disk\Downloads\Website.

**Comment by LukachoLombardi** [comment]
add quotation marks around your filepath. Btw this doesn't realyl have anything to do with this script, it's just something that happens when you use file paths with spaces in their name
